-- ============================================================================
-- deliayjuan — Esquema completo de Supabase
-- ============================================================================
-- Ejecuta este archivo completo en: Supabase Dashboard → SQL Editor → New query
-- Es idempotente: puedes volver a correrlo sin romper nada (usa IF NOT EXISTS /
-- ON CONFLICT DO NOTHING donde aplica).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. EXTENSIONES
-- ----------------------------------------------------------------------------
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. TABLA: invitados
-- ----------------------------------------------------------------------------
create table if not exists public.invitados (
  id         bigint generated by default as identity primary key,
  token      uuid not null default gen_random_uuid(),
  nombre     text not null,
  apellido   text not null,
  cupos      integer not null default 1 check (cupos > 0 and cupos <= 20),
  mesa       integer check (mesa is null or mesa > 0),
  confirma   boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invitados_token_key unique (token)
);

comment on table public.invitados is 'Invitados de la boda: un registro por invitación/token enviado.';
comment on column public.invitados.token is 'Token único (UUID) usado en la URL /invitacion/:token';
comment on column public.invitados.cupos is 'Número de personas que cubre esta invitación';
comment on column public.invitados.mesa is 'Número de mesa asignada (opcional)';
comment on column public.invitados.confirma is 'NULL = pendiente, true = confirma asistencia, false = no asiste';

create index if not exists invitados_token_idx on public.invitados (token);
create index if not exists invitados_confirma_idx on public.invitados (confirma);

-- Trigger: mantener updated_at actualizado automáticamente
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists invitados_set_updated_at on public.invitados;
create trigger invitados_set_updated_at
  before update on public.invitados
  for each row
  execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY — invitados
-- ----------------------------------------------------------------------------
-- NOTA DE SEGURIDAD (igual que el proyecto original):
-- Esta app NO usa Supabase Auth; el panel /admin solo valida contra variables
-- de entorno en el cliente (VITE_ADMIN_EMAIL / VITE_ADMIN_PASSWORD) y guarda
-- la sesión en localStorage. Tanto los invitados como el admin acceden con la
-- misma "anon key", así que las políticas de abajo son abiertas a propósito
-- para replicar el comportamiento actual. Es aceptable para una invitación
-- de boda (tokens son UUID no adivinables), pero NO lo uses para datos
-- sensibles. Si más adelante quieres endurecerlo, migra el panel /admin a
-- Supabase Auth real y restringe INSERT/UPDATE/DELETE a `authenticated`.

alter table public.invitados enable row level security;

drop policy if exists "invitados_select_public" on public.invitados;
create policy "invitados_select_public"
  on public.invitados
  for select
  to anon, authenticated
  using (true);

drop policy if exists "invitados_insert_public" on public.invitados;
create policy "invitados_insert_public"
  on public.invitados
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "invitados_update_public" on public.invitados;
create policy "invitados_update_public"
  on public.invitados
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "invitados_delete_public" on public.invitados;
create policy "invitados_delete_public"
  on public.invitados
  for delete
  to anon, authenticated
  using (true);

-- Nota: la invitación ya no usa Supabase Storage; todas las imágenes viven en
-- src/assets. Si ya creaste los buckets 'wedding-photos' e 'icons', puedes borrarlos.

-- ----------------------------------------------------------------------------
-- 3. SEED — Invitado de prueba (opcional, bórralo cuando ya no lo necesites)
-- ----------------------------------------------------------------------------
insert into public.invitados (token, nombre, apellido, cupos, mesa, confirma)
values ('00000000-0000-4000-8000-000000000001', 'Invitado', 'Demo', 2, 1, null)
on conflict (token) do nothing;

-- ============================================================================
-- Fin del script.
-- Prueba la invitación demo en: /invitacion/00000000-0000-4000-8000-000000000001
-- ============================================================================
